### ISSUE TITLE
issues opening UI

### ISSUE THREAD

**Issue by Thegasman2000** [Scottapotamas/AS7265x-triad-ui#1]
When unzipped I have navigated to the folder in terminal. 

  arc info returns:
  Arc details
  Arc version: 0.4.11
  Release channel: latest
  Bolt channel: production
  Registry channel: production

  Dependency details
  Node version: 18.8.0
  Yarn version: 3.0.1-rc.2.git.20201109.hash-fe1419471e

  User details
  Email: XXX@gmail.com

  This version of Arc is up to date.

 arc install returns:
➤ YN0000: └ Completed in 1m 13s
➤ YN0000: Failed with errors in 1m 14s

and arc start:
⠧ Compiling application and transport bundles... Usage Error: The project in /Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/package.json doesn't seem to have been installed - running an install there might help

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
Could not start development environment:
exit status 1

Any ideas?

**Comment by Mike-Dax** [comment]
We've found an issue with a certain package (fsevents) having a different checksum when installing on Linux vs MacOS.

If you run `YARN_CHECKSUM_BEHAVIOR=update arc install`, that should override the checksum in the lock file.

I'll try and fix this upstream, but let me know if that lets you install it.

**Comment by Thegasman2000** [comment]
Thanks I tried that... 

➤ YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:393:5)
    at PassThrough.onclose (node:internal/streams/end-of-stream:142:30)
    at PassThrough.emit (node:events:513:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
➤ YN0000: └ Completed in 1m 7s
➤ YN0000: Failed with errors in 1m 7s
exit status 1

**Comment by Mike-Dax** [comment]
I can replicate that error on Node v18, if you downgrade to the LTS release of Node (v16.17.0) it should work.

Assuming you used `nvm` to install node:

```
nvm install 16.17.0
nvm use 16

YARN_CHECKSUM_BEHAVIOR=update arc install
arc start
```

**Comment by Thegasman2000** [comment]
Done: 

Apples-Air:interface XXXX$ YARN_CHECKSUM_BEHAVIOR=update arc install
Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at Object.deserialize (node:v8:366:7)
    at Re.restoreInstallState (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:309:854)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Dp.execute (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:348:14565)
    at async Dp.validateAndExecute (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:197:620)
    at async ts.run (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:211:1846)
    at async ts.runExit (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:211:2013)
    at async i (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:310:12318)
    at async r (/Users/Reid/Documents/aMeter/ElectricUItriad/AS7265x-triad-ui-master/interface/.yarn/releases/yarn.js:310:10558)
exit status 1

Apples-Air:interface XXXX$ arc info

  Arc details
  Arc version: 0.4.11
  Release channel: latest
  Bolt channel: production
  Registry channel: production

  Dependency details
  Node version: 16.17.0
  Yarn version: 3.0.1-rc.2.git.20201109.hash-fe1419471e

  User details
  Email: XXXX@gmail.com

  This version of Arc is up to date.

**Comment by Mike-Dax** [comment]
I've updated the project with the latest version of our template and tested it on my 2013 MBP and it seems to work with both Node 16 and Node 18.

Can you please try pulling the latest version, `arc install` `arc start`?
